### ISSUE TITLE
Remote wsl fails to open integrated terminal after upgrade to vscode 1.75.0

### ISSUE THREAD

**Issue by Westixy** [sonowz/vscode-remote-wsl-nixos#4]
Just noticed this today. Don't think it is related to this project, but i thought it could be a good place to have a workaround or a fix.

As It is just mentioned, I had a working vscode instance using NixOS-wsl. 

Integrated terminal do not work anymore after update from `v1.74.3` to `v1.75.0` 

This is the error provided by vscode:
```
The terminal process failed to launch: A native exception occurred during launch (posix_spawn failed: No such file or directory).
```

As a way to make it work i just downgraded the version of vscode using choco:
```sh
choco uninstall vscode -y
choco install vscode --version=1.74.3
```

**Comment by sonowz** [comment]
Thank you for sharing the issue!
I recently updated my vscode to `v1.76.0` and it's working well.
Seems like the issue is fixed in this version.

Have a good day!

**Comment by arouzing** [comment]
I'm still running into this issue, interestingly enough. I've updated to the latest version as a test, yet it still exists.

**Comment by Westixy** [comment]
I tried as well to upgrade to `1.76.0` and it is still failing. Maybe it is not strictly linked to the version 🤔

**Comment by sonowz** [comment]
That's a bummer :(
What version of NixOS are you using? Are you using WSL distro from https://github.com/nix-community/NixOS-WSL?
I'm running NixOS 22.05 with that distro.

**Comment by Westixy** [comment]
Tested #5 and it works fine for 1.77 
Thanks @justinkb
